### ISSUE TITLE
No Animation in version v1.0.0-rc1

### ISSUE THREAD

**Issue by 0x090909** [bherbruck/svelte-echarts#19] opened 2024-06-14 20:09 UTC
I just upgraded, and my charts dont animate anymore. 

Is there something changed in the api? 

Thanks

**Comment by zerdox-scalr** [comment] 2024-06-14 20:36
I am currently solving the same problem.. Trying to find the solution. LMK if you find anything

**Comment by zerdox-scalr** [comment] 2024-06-14 20:51
> Is there something changed in the api?

Was it working for on previous version? I've just installed this package. I'll try to downgrade but not sure if I can rewrite my code easily

**Comment by bherbruck** [comment] 2024-06-14 20:59
You need to `use(TransformComponent)` with the new tree-shakable API.
See the example [here](https://github.com/bherbruck/svelte-echarts/blob/287cc70ad62d6e3aee32b61981f19a9da57ba6be/src/routes/%2Bpage.svelte#L22)

**Comment by 0x090909** [comment] 2024-06-14 21:30
> You need to `use(TransformComponent)` with the new tree-shakable API. See the example [here](https://github.com/bherbruck/svelte-echarts/blob/287cc70ad62d6e3aee32b61981f19a9da57ba6be/src/routes/%2Bpage.svelte#L22)

Its very strange Im already using that actually, what Im noticing is that the line is not animating anymore, the only thing that is animating are the dots that form the line in the chart.


https://github.com/bherbruck/svelte-echarts/assets/16927059/06e0a194-c4ec-469c-9ddc-ee63bd75c5e4

**Comment by 0x090909** [comment] 2024-06-14 21:31
@zerdox-scalr doesnt change much

**Comment by zerdox-scalr** [comment] 2024-06-14 21:54
> Its very strange Im already using that actually, what Im noticing is that the line is not animating anymore, the only thing that is animating are the dots that make the line in the chart.

Yeah! I am experiencing same thing with line chart. I would like to see animation like this: https://echarts.apache.org/examples/en/editor.html?c=line-simple

It can be configured using animation properties (delay, easing, duration) on series: 
```
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line',
      animationEasing: "linear",
      animationDuration: 2000
    }
  ]
```

It doesn't work for both renderers for me

**Comment by zerdox-scalr** [comment] 2024-06-15 12:28
any workaround, guys? @bherbruck have you been able to reproduce?

**Comment by zerdox-scalr** [comment] 2024-06-15 17:30
@bherbruck you got any warnings related to echarts? i got one about dom.width and height. not sure what to do with it, can it be the cause?

**Comment by bherbruck** [comment] 2024-06-18 12:28
It looks like the problem is the `ResizeObserver`. I don't have a fix for it right now as `ResizeObserver` fires on page load and `echarts` seems cancel animations during resize events. All the fixes I've tried cause "pop-in" and layout shifts which is much uglier than not having an animation IMO. I'll continue looking into it.

**Comment by bherbruck** [comment] 2024-06-18 13:59
fixed in https://github.com/bherbruck/svelte-echarts/commit/0e8d6b0be94ac6e74684045cec31817fee7ba0d4

**Closed by bherbruck** 2024-06-18 13:59 UTC
Labels: bug
